# Generated by Django 5.1.5 on 2025-04-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_savedset'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
