# Generated by Django 5.1.6 on 2025-03-31 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_favoriteset_delete_favoritedeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_review_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
