# Generated by Django 5.1.5 on 2025-03-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_favoriteset_delete_favoritedeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
    ]
