# Generated by Django 5.2 on 2025-04-07 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0005_flashcard_is_learned_flashcard_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cards_viewed", models.IntegerField(default=0)),
                ("time_spent", models.IntegerField(default=0)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "flashcard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.flashcard",
                    ),
                ),
                (
                    "learned_cards",
                    models.ManyToManyField(
                        blank=True, related_name="learned_by", to="mysite.flashcard"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
