# Generated by Django 5.2 on 2025-04-07 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0007_useractivity_quizzes_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractivity",
            name="quizzes_completed",
        ),
        migrations.AddField(
            model_name="useractivity",
            name="recent_flashcard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recently_viewed",
                to="mysite.flashcard",
            ),
        ),
    ]
