# Generated by Django 5.2 on 2025-04-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0008_remove_useractivity_quizzes_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="quizzes_completed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
