# Generated by Django 5.2 on 2025-04-07 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0009_useractivity_quizzes_completed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractivity",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="flashcard",
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="cards_viewed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="recent_flashcard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mysite.flashcard",
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="time_spent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
